# This file was generated by GoReleaser. DO NOT EDIT.
cask "swat" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a661dcea80ad7d7a817d95c20c49aff7ed205150da8246e504bfe9a74093d230"
      url "https://github.com/keenanlk/swat/releases/download/v#{version}/swat_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2f88ef7ed4448d934ead609f05b72de031da4efc717962546eaf97e32749061"
      url "https://github.com/keenanlk/swat/releases/download/v#{version}/swat_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f6654ee549d956abc530be5dca50c6d503dc7525e807fb7e4d70dd744e804edd"
      url "https://github.com/keenanlk/swat/releases/download/v#{version}/swat_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "58cc7fe829b7346e15202151a5d90215c6acc2f1cbbdc9fa98ef621f4ab7e2b9"
      url "https://github.com/keenanlk/swat/releases/download/v#{version}/swat_linux_amd64.tar.gz"
    end
  end

  name "swat"
  desc "Send Claude Code agents after the GitHub issues assigned to you"
  homepage "https://github.com/keenanlk/swat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swat"]
    end
  end

  # No zap stanza required
end
